sudo: required
dist: trusty
before_install:
- docker pull debian:testing
script:
- ./build.sh
deploy:
  provider: releases
  api_key:
    secure: E1II4CWMiwB3OrX3sjAsb1ePue4flG3pXcgMulQNAQd1csRA74pGqc67hWVTNJZ9kZjZHA0U2sctSUtep9B0C5LTpOHHXBUbnNtXXZwmHCFvaKJJuy+docvs8/f+H5B0pSoT8H5ydvs3gCuC+FJ1pv//L34J9gPRmam54wsyVMM=
  file: ./Diego Toharia - CV (English).pdf
  on:
    repo: deigote/cv
    tags: true
